Feature/account page styling
yuna-iwata/dino-frontend-v2 pull request #24
Opened 2023-01-16 18:56 UTC by Mariam-mohamed110

- changed header to be in the middle
- added a selection of avatars to change in user profile
- some minor changes in styling across different files

2023-01-16 19:01 UTC, louisglan commented on src/App.js
> +    console.log(`${baseUrl}${itemData[avatar - 1]["img"]}`);
this console.log needs removing

2023-01-16 19:27 UTC, louisglan commented on src/App.js
> +    setCurrentAvatar(`${baseUrl}${itemData[avatar - 1]["img"]}`);
I think using 'avatar - 1' renders the id useless - might be worth removing the id keys from each object in itemData

2023-01-16 19:29 UTC, yuna-iwata commented
netlify deploy has failed

2023-01-16 19:34 UTC, louisglan commented on src/Components/AccountPageSubPages/AvatarSelection.jsx
> +  const itemData = [
Could have this passed down as a prop from App. Same with baseUrl

2023-01-16 19:35 UTC, louisglan commented on src/Components/AccountPageSubPages/AvatarSelection.jsx
> +        {itemData.map((item) => (
I feel this should map onto a component which should have it's own file

2023-01-16 19:39 UTC, louisglan requested changes
In addition to below changes, should be made to deploy to netlify

2023-01-17 11:06 UTC, louisglan approved these changes
Would be nice to change game.key !== null to game.key but otherwise everything looks great

2023-01-17 11:06 UTC, merged